# permissions for end users to edit dataflowengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataflowengine-editor-role
rules:
- apiGroups:
  - dataflow.pingcap.com
  resources:
  - dataflowengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataflow.pingcap.com
  resources:
  - dataflowengines/status
  verbs:
  - get
