# permissions for end users to view dataflowengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataflowengine-viewer-role
rules:
- apiGroups:
  - dataflow.pingcap.com
  resources:
  - dataflowengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataflow.pingcap.com
  resources:
  - dataflowengines/status
  verbs:
  - get
