apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: dataflow.pingcap.com/v1
kind: DataflowEngine
metadata:
  namespace: dev
  name: dataflowengine
spec:
  image: steponce7/dataflow:test
  master:
    name: server-master
    size: 1
    Ports: 10240
    clusterTag: false
  executor:
    name: server-executor
    size: 1
    Ports: 10241
    clusterTag: false
  frameStandalone:
    name: frame-mysql-standalone
    image: mysql:5.7
    platform: linux/amd64
    port: 3306
    clusterTag: false
  userStandalone:
    name: user-etcd-standalone
    size: 1
    image: quay.io/coreos/etcd
    ports:
      - 2379
      - 2380
    clusterTag: false
