apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: dataflow.pingcap.com/v1
kind: DataflowEngine
metadata:
  namespace: dev
  name: dataflowengine-sample
spec:
  frameStandalone:
    name: mysql-standalone-sample
    image: mysql:5.7
    port: 3306
    clusterTag: false
  userStandalone:
    name: etcd-demo
    size: 3
    image: quay.io/coreos/etcd
    ports:
      - 2379
      - 2380
