apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: dataflow.pingcap.com/v1
kind: DataflowEngine
metadata:
  namespace: dev
  name: dataflowengine-sample
spec:
  name: tangMysql
  image: mysql:5.6
  ports: 3306
