apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: dataflow.pingcap.com/v1
kind: DataflowEngine
metadata:
  namespace: dev
  name: dataflowengine
spec:
  frameStandalone:
    name: frame-mysql-standalone
    image: mysql:5.7
    platform: linux/amd64
    port: 3306
    clusterTag: false
